services:
  web:
    build: .
    command: ./docker/puma.sh
    port: 3000
    environment:
      - AVENGINE
      - DASHBOARD_API_KEY
      - RACK_ENV
      - RAILS_ENV
      - SECRET_KEY_BASE
      - DATABASE_URL
      - REDIS_URL
      - RAILS_MAX_THREADS
      - RAILS_SERVE_STATIC_FILES
    labels:
      - convox.port.443.protocol=https
      - convox.deployment.minimum=50
      - convox.health.path=/healthcheck
      - convox.health.port=3000
      - convox.health.timeout=3
