version: "3.9"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - redis
  redis:
    image: "redis:alpine"
  db:
    image: postgres:latest  # Ensure you are using an appropriate version
    command: ["postgres", "-c", "hba_file=/var/lib/postgresql/data/pg_hba.conf"]
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    environment:
      POSTGRES_PASSWORD: password
