web:
  labels:
    - convox.port.443.protocol=https
  command: bash -c "bundle exec puma -C config/puma.rb"
  ports:
    - "443:3000"
worker:
  command: bash -c "clamd && bundle exec sidekiq -C ./config/sidekiq.yml"
