web:
  build: .
  labels:
    - convox.port.443.protocol=https
    - convox.deployment.minimum=50
    - convox.health.path=/healthcheck
    - convox.health.port=3000
    - convox.health.timeout=3
  command: ["/sbin/my_init"]
  ports:
    - "443:3000"
worker:
  build: .
  command: ["bin/worker"]
