web: &web
  build: .
  command: bundle exec puma -C config/puma.rb
  environment:
  ports:
    - "443:3000"
  volumes:
    - .:/app
worker:
  <<: *web
  ports: []
  command: bundle exec sidekiq -C ./config/sidekiq.yml
