default: &default
  max_file_size_mb: 50

development:
  <<: *default
  dashboard_api_key: "vigilion"
  engines:
    clamav: "clamdscan"
    clamav_opts: "--stream --stdout"
    avg: "avgscan"
    avg_opts: "-P -a -w -j"
    eset: "esets_scan"

test:
  <<: *default
  dashboard_api_key: "vigilion"
  engines:
    clamav: "clamdscan"
    clamav_opts: "--stream --stdout"
    avg: "avgscan"
    avg_opts: "-P -a -w -j -i"
    eset: "esets_scan"

staging:
  <<: *default
  dashboard_api_key:  <%= ENV["DASHBOARD_API_KEY"] %>
  engines:
    clamav: "clamdscan"
    avg: "avgscan"
    avg_opts: "-P -a -w -j"
    eset: "esets_scan"

production:
  <<: *default
  dashboard_api_key:  <%= ENV["DASHBOARD_API_KEY"] %>
  engines:
    clamav: "clamdscan"
    avg: "avgscan"
    avg_opts: "-P -a -w -j"
    eset: "esets_scan"
