development:
  av_engine: "clamdscan"
  dashboard_api_key: "vigilion"

test:
  av_engine: "clamdscan"
  dashboard_api_key: "vigilion"

production:
  av_engine: <%= ENV["AVENGINE"] %>
  dashboard_api_key:  <%= ENV["DASHBOARD_API_KEY"] %>
