default: &default
  max_file_size_mb: 50

development:
  <<: *default
  dashboard_api_key: "vigilion"
  engines:
    clamav: "clamdscan"
    avg: "avgscan"
    eset: "esets_scan"

test:
  <<: *default
  dashboard_api_key: "vigilion"
  engines:
    clamav: "clamdscan"
    avg: "avgscan"
    eset: "esets_scan"

staging:
  <<: *default
  dashboard_api_key:  <%= ENV["DASHBOARD_API_KEY"] %>
  engines:
    clamav: <%= ENV["CLAMAV_COMMAND"] %>
    avg: <%= ENV["AVG_COMMAND"] %>
    eset: <%= ENV["ESET_COMMAND"] %>

production:
  <<: *default
  dashboard_api_key:  <%= ENV["DASHBOARD_API_KEY"] %>
  engines:
    clamav: <%= ENV["CLAMAV_COMMAND"] %>
    avg: <%= ENV["AVG_COMMAND"] %>
    eset: <%= ENV["ESET_COMMAND"] %>
