common: &common
  adapter: postgresql
  encoding: utf8

development:
  <<: *common
  database: vigilion_scanner_development
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *common
  database: vigilion_scanner_test

staging:
  <<: *common
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *common
  url: <%= ENV['DATABASE_URL'] %>
