default: &default
  adapter: postgresql
  encoding: utf8
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: vigilion_scanner_dev

test:
  <<: *default
  database: vigilion_scanner_test

staging:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
