default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 5000
  username:
  password:
  host:
  port:


development: &development
  <<: *default
  database: vs_dev

test: &test
  <<: *default
  database: vs_test

production: &production
  <<: *default
  database: vs_prod


default_env:
  <<: *development
