common: &common
  adapter: postgresql
  encoding: utf8

development:
  <<: *common
  database: vigilion_scanner_development
  username: postgres
  host: db

test:
  <<: *common
  database: vigilion_scanner_test
  username: postgres
  host: db

staging:
  <<: *common
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *common
  url: <%= ENV['DATABASE_URL'] %>