common: &common
  adapter: postgresql
  encoding: utf8

development:
  <<: *common
  database: vigilion_scanner_development
  url: <%= ENV['DATABASE_URL'] || "postgresql://#{ENV['POSTGRES_ENV_POSTGRES_USERNAME']}:#{ENV['POSTGRES_ENV_POSTGRES_PASSWORD']}@#{ENV['POSTGRES_PORT_5432_TCP_ADDR']}:#{ENV['POSTGRES_PORT_5432_TCP_PORT']}" %>

test:
  <<: *common
  database: vigilion_scanner_test

staging:
  <<: *common
  url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *common
  url: <%= ENV['DATABASE_URL'] %>
