###############
# General
###############

DatabaseDirectory /var/lib/clamav
DatabaseOwner app
LogSyslog false
LogTime yes
PidFile /tmp/freshclam.pid
#Foreground true

###############
# Updates
###############

DatabaseMirror db.local.clamav.net
DatabaseMirror database.clamav.net
MaxAttempts 5
ScriptedUpdates yes
SafeBrowsing false
Bytecode yes
ReceiveTimeout 240
