name: Ruby on Rails CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: vigilion_scanner_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.7' # Adjust the Ruby version to match your project's version

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libpq-dev clamav clamav-daemon
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Start ClamAV daemon
      run: |
        sudo systemctl start clamav-daemon

    - name: Setup Database
      env:
        RAILS_ENV: test
        DATABASE_URL: postgres://postgres:password@localhost:5432/vigilion_scanner_test
      run: |
        bin/rails db:create
        bin/rails db:schema:load

    - name: Run tests
      env:
        RAILS_ENV: test
        DATABASE_URL: postgres://postgres:password@localhost:5432/vigilion_scanner_test
      run: bundle exec rspec